version: '3'

services:
  budget:
    build: .
    restart: on-failure
    command: npm run dev -- --port 3000 --noEnvironment --host 0.0.0.0 --showDuration
    environment:
      MONGO_URL: "mongodb://mongo:27017"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.3-bionic
    restart: on-failure
    ports:
      - "27017:27017"
